version: "3.8"

services:
  mongo:
    image: mongo:6.0
    container_name: my-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: mi_db
    volumes:
      - mongo_data:/data/db
    networks:
      - my-network

  backend:
    build: ./backend
    container_name: my-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://admin:secret@mongo:27017/mi_db?authSource=admin
      - PORT=5000
    depends_on:
      - mongo
    volumes:
      - ./backend:/usr/src/app           # backend code
      - ./frontend:/usr/src/frontend     # frontend code, para que exista /usr/src/frontend/index.html
      - /usr/src/app/node_modules
    networks:
      - my-network

volumes:
  mongo_data:

networks:
  my-network:
    driver: bridge
